# Generated by Django 5.2.15 on 2026-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ООО «ДемоПласт»', max_length=255, verbose_name='Название компании')),
                ('phone_sales', models.CharField(blank=True, max_length=32, verbose_name='Телефон — отдел продаж')),
                ('phone_sales_person', models.CharField(blank=True, max_length=255, verbose_name='ФИО — продажи')),
                ('phone_production', models.CharField(blank=True, max_length=32, verbose_name='Телефон — производство')),
                ('phone_production_person', models.CharField(blank=True, max_length=255, verbose_name='ФИО — производство')),
                ('phone_accounting', models.CharField(blank=True, max_length=32, verbose_name='Телефон — бухгалтерия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail бухгалтерии')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat_id (уведомления)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес производства')),
                ('work_hours', models.CharField(blank=True, max_length=128, verbose_name='Рабочие дни')),
                ('work_hours_weekend', models.CharField(blank=True, max_length=128, verbose_name='Выходные дни')),
                ('map_query', models.CharField(blank=True, max_length=255, verbose_name='Запрос для Яндекс.Карт')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('okpo', models.CharField(blank=True, max_length=14, verbose_name='ОКПО')),
                ('account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('bank', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
