# Generated by Django 5.2.15 on 2026-06-10 16:34

from django.db import migrations


# Демо-данные вымышленной компании «ДемоПласт». Все контакты и реквизиты
# фиктивны: телефоны из диапазона 495 000-00-XX, ИНН/ОГРН/счета — плейсхолдеры.
DATA = {
    "company_name": "ООО «ДемоПласт»",
    "phone_sales": "+7 495 000-00-00",
    "phone_sales_person": "Иванова Анна Петровна",
    "phone_production": "+7 495 000-00-01",
    "phone_production_person": "Петров Иван Сергеевич",
    "phone_accounting": "+7 495 000-00-02",
    "email": "info@demoplast.example",
    "telegram_chat_id": "",
    "address": "г. Москва, ул. Промышленная, д. 1",
    "work_hours": "ПН–ПТ · 08:00–17:00",
    "work_hours_weekend": "СБ–ВС: выходной",
    "map_query": "Москва, улица Промышленная, 1",
    "legal_address": "101000, г. Москва, ул. Промышленная, д. 1",
    "inn": "7700000000",
    "kpp": "770001001",
    "ogrn": "1107700000000",
    "okpo": "00000000",
    "account": "40702810000000000000",
    "bank": "АО «Демо-Банк», г. Москва",
    "bik": "044500000",
    "corr_account": "30101810000000000000",
}


def seed(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.update_or_create(pk=1, defaults=DATA)


def unseed(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
