# Generated by Django 5.2.15 on 2026-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_metrika_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='email',
            new_name='email_accounting',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_sales',
            field=models.EmailField(blank=True, help_text='Адрес для заявок. На него приходят письма о новых заявках с сайта.', max_length=254, verbose_name='E-mail отдела продаж'),
        ),
    ]
