# Generated by Django 5.2.15 on 2026-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_email_sitesettings_email_accounting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_notifications',
            field=models.EmailField(blank=True, help_text='Адрес, на который сайт шлёт письма о новых заявках. Не путать с e-mail продаж в «Контактах» — здесь только для уведомлений.', max_length=254, verbose_name='E-mail для уведомлений'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_amocrm_enabled',
            field=models.BooleanField(default=False, help_text='Требует настройки интеграции amoCRM (в .env) и авторизации.', verbose_name='Отправлять заявки в amoCRM'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_email_enabled',
            field=models.BooleanField(default=True, help_text='Если включено — о новой заявке приходит письмо на адрес ниже.', verbose_name='Отправлять заявки на email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_telegram_enabled',
            field=models.BooleanField(default=False, help_text='Требует токен бота (в .env) и chat_id (в «Контактах»).', verbose_name='Отправлять уведомления в Telegram'),
        ),
    ]
