# Generated by Django 5.2.15 on 2026-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Короткая метка-ярлык на фото карточки (напр. «Евроканистра», «Круглая»).', max_length=50, verbose_name='Метка'),
        ),
    ]
